---
- hosts: web_servers
  become: true
  tasks:
    - name: Update the apt-get (yum in centos) repository #this name can be anything to help me understand the task
      apt:
        update_cache: yes

    - name: Update repo and Install nginx
      apt: 
        name: "nginx"
        state: present # This means that if the application has been installed, Ansible will not overwrite it

   # DON'T START THESE STEPS UNTIL I RUN THE ANSIBLE PLAYBOOK WITH THE WEBSERVERS, AND THE NGINX INSTALLATION [LINES 1 - 12] 
    - name: Create folder for website
      file:
        path: "/var/www/{{ website_name }}"
        state: directory

    - name: Delete sites-enable and sites-available files
      file:
        path: "{{ item }}"
        state: absent
      with_items: # This is how you do an ansible loop
        - "/etc/nginx/sites-enabled/default"
        - "/etc/nginx/sites-available/default"
      notify:
        - Restart nginx  

    - name: Add webpage to servers
      template:
        src: "index.html.tpl"
        dest: "/var/www/{{ website_name }}/index.html"
      notify:
        - Restart nginx

    - name: Configure nginx with the new config file
      template:
        src: "default.tpl"
        dest: "/etc/nginx/sites-available/{{ website_name }}"
      notify:
        - Restart nginx
           
    - name: Create symlink for config file
      file:
        src: "/etc/nginx/sites-available/{{ website_name }}"
        dest: "/etc/nginx/sites-enabled/{{ website_name }}"
        state: link
      notify:
        - Restart nginx

  handlers:
    - name: Restart nginx 
      service:
        name: nginx
        state: restarted

 
    